### PR TITLE
1

### PR DESCRIPTION
**Pull request by NorbertBodziony**

### CODE REVIEW

**Comment by NorbertBodziony** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>d5252b6</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://synthetify-webapp-e1wus8k39-synthetify.vercel.app'>https://synthetify-webapp-e1wus8k39-synthetify.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/synthetify/synthetify-webapp/7iMqaLaieiZHUkkrjDtsjNrQ7KYs'>https://vercel.com/synthetify/synthetify-webapp/7iMqaLaieiZHUkkrjDtsjNrQ7KYs</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/Synthetify/synthetify-webapp/actions/runs/1500430369)

**Comment by NorbertBodziony** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>0559266</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://synthetify-webapp-8qiqe8gkz-synthetify.vercel.app'>https://synthetify-webapp-8qiqe8gkz-synthetify.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/synthetify/synthetify-webapp/2egsSechfXFrTShnG3LZxnyuX7Em'>https://vercel.com/synthetify/synthetify-webapp/2egsSechfXFrTShnG3LZxnyuX7Em</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/Synthetify/synthetify-webapp/actions/runs/1500454475)

**Comment by NorbertBodziony** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>575043c</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://synthetify-webapp-qhnduw1vb-synthetify.vercel.app'>https://synthetify-webapp-qhnduw1vb-synthetify.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/synthetify/synthetify-webapp/ArLJG274X8pGcNa6nifsL2mAeYwb'>https://vercel.com/synthetify/synthetify-webapp/ArLJG274X8pGcNa6nifsL2mAeYwb</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/Synthetify/synthetify-webapp/actions/runs/1500500392)

**Comment by NorbertBodziony** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>24a085a</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://synthetify-webapp-lh0kd5zpy-synthetify.vercel.app'>https://synthetify-webapp-lh0kd5zpy-synthetify.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/synthetify/synthetify-webapp/Gac18cyM57zfC7juJ4YNTusRqVsL'>https://vercel.com/synthetify/synthetify-webapp/Gac18cyM57zfC7juJ4YNTusRqVsL</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/Synthetify/synthetify-webapp/actions/runs/1500507189)

**Review by wojciech-cichocki — APPROVED** [review]

**Comment by NorbertBodziony** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>aa91d51</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://synthetify-webapp-in7474ohg-synthetify.vercel.app'>https://synthetify-webapp-in7474ohg-synthetify.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/synthetify/synthetify-webapp/4HyHDA8DRbzYL16WWx6hBd7Y7Nq4'>https://vercel.com/synthetify/synthetify-webapp/4HyHDA8DRbzYL16WWx6hBd7Y7Nq4</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/Synthetify/synthetify-webapp/actions/runs/1503332300)

**Pull request merged**
